"""empty message

Revision ID: 45dad174ab95
Revises: 0fe11dbf99ef
Create Date: 2017-02-27 20:01:46.278163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45dad174ab95'
down_revision = '0fe11dbf99ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_categories_create_time'), 'categories', ['create_time'], unique=False)
    op.add_column('posts', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_posts_create_time'), 'posts', ['create_time'], unique=False)
    op.drop_index('ix_posts_timestamp', table_name='posts')
    with op.batch_alter_table('posts') as batch_op:
        batch_op.drop_column('timestamp')
    # op.drop_column('posts', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.create_index('ix_posts_timestamp', 'posts', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_posts_create_time'), table_name='posts')
    op.drop_column('posts', 'create_time')
    op.drop_index(op.f('ix_categories_create_time'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
