"""empty message

Revision ID: 60da23641850
Revises: d96fb9f72134
Create Date: 2017-03-07 16:02:56.597071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60da23641850'
down_revision = 'd96fb9f72134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
