"""empty message

Revision ID: cc11c032c81e
Revises: 8644046b7af0
Create Date: 2017-03-10 16:04:11.110183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc11c032c81e'
down_revision = '8644046b7af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(
        'is_administrator', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_administrator')
    # ### end Alembic commands ###
